### ISSUE TITLE
How to use this on windows 10?

### ISSUE THREAD

**Issue by glazedtorus** [ArmandSy/InstaLocTrack#4]
The sudo command to install selenium webdriver is not available on windows so I was wondering if there is a way to use it on windows machines.

**Comment by bernsteining** [comment]
Hey, 

I don't know very much about Windows, however you can look [how to install selenium on Windows](https://mundrisoft.com/tech-bytes/install-selenium-webdriver-windows/). Plus, you can try to run the tool with Docker (cf. Dockerfile in the repo).

Also, you can use [WSL (Windows Subsystem for Linux)](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) and run it as if you were on Linux.

However, it looks like instagram changed a few things about the layout of their website and hence instaloctrack doesn't work anymore. I could refactor the code to make it work again but I lack time to do so, and anyway I would restart the project from scratch, old code needs a lot of cleanup :). 

Peace,

**Comment by glazedtorus** [comment]
Ok I will go over the code base and try to find the issue. But I'm new to python and trying to understand how the code works is difficult for me, but I will try. This repo is very cool so I hope it works properly again, maybe as a web app or something one day.
