### ISSUE TITLE
Python\Python39\lib\encodings\cp1252.py", line 23, in decode       return codecs.charmap_decode(input,self.errors,decoding_table)[0]   UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 363: character maps to <undefined>

### ISSUE THREAD

**Issue by httpanand** [ArmandSy/InstaLocTrack#6]
Python\Python39\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 363: character maps to <undefined>

**Comment by bernsteining** [comment]
O'rite

**Comment by httpanand** [comment]
?
