### ISSUE TITLE
Error with the installation

### ISSUE THREAD

**Issue by Islhaw** [ArmandSy/InstaLocTrack#8]
Hi ! I have an issue when I try to install the program. Could you please help me to understand what is happening ? Thanks.

Here is what I have in PowerShell: 

PS C:\Users\User\instaloctrack> pip3 install .
Processing c:\users\user\instaloctrack
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\User\instaloctrack\setup.py", line 4, in <module>
          long_description = fh.read()
                             ^^^^^^^^^
        File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 376: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by YLA1018** [comment]
I've same problem, if you have a solution , i'm ready !

**Comment by albotroz** [comment]
seems like it is dead, or?

**Comment by bernsteining** [comment]
Yes this project was a school project a did 4-5 years ago. 

Even if pip install would work, I doubt the scraping logic would still work since Instagram evolved a lot in 4 years, I guess.

You could rewrite it using [playwright](https://github.com/microsoft/playwright), it shouldn't be that hard IMO, and it can be a first fun project to learn webscraping.

I'm archiving this project as I won't touch it anymore.
